### ISSUE TITLE
java.util.ConcurrentModificationException with codelens

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/lsp4ij#172]
I don't know how to reproduce, but I had this error:

```

Exception during computeCodeVision for LSPCodeLensProvider

java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at com.redhat.devtools.lsp4ij.features.codelens.LSPCodeLensProvider.computeCodeVision(LSPCodeLensProvider.java:131)
	at com.redhat.devtools.lsp4ij.features.codelens.LSPCodeLensProvider.computeCodeVision(LSPCodeLensProvider.java:55)
	at com.intellij.codeInsight.codeVision.CodeVisionHost$calculateFrontendLenses$2.invoke(CodeVisionHost.kt:440)
	at com.intellij.codeInsight.codeVision.CodeVisionHost$calculateFrontendLenses$2.invoke(CodeVisionHost.kt:409)
	at com.intellij.codeInsight.codeVision.CodeVisionHost.executeOnPooledThread$lambda$12$lambda$11(CodeVisionHost.kt:497)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.codeInsight.codeVision.CodeVisionHost.executeOnPooledThread$lambda$12(CodeVisionHost.kt:497)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by angelozerr** [comment]
I close this issue since it has been fixed with https://github.com/redhat-developer/lsp4ij/commit/756833c25c88c43f2600d7f13948edf0fcb70786#diff-34fb6347aa00e7086bde446e63f250e153634b073af14b68dea00f4957fa0ff8R85
