### ISSUE TITLE
The usual "CancellationException" but this time in LSP4IJ rather than in Quarkus Tools

### ISSUE THREAD

**Issue by mfortunat** [redhat-developer/lsp4ij#240]
IJ 2024.1 Build #IU-241.14494.240, built on March 28, 2024
LSP4IJ 0.0.1-20240419-012629
--- --- --- --- --- --- 
Doing normal coding stuff...
--- --- --- --- --- --- 
Exception during computeCodeVision for LSPCodeLensProvider

java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2480)
	at com.redhat.devtools.lsp4ij.internal.PromiseToCompletableFuture.lambda$bind$0(PromiseToCompletableFuture.java:96)
	at org.jetbrains.concurrency.AsyncPromise.onError$lambda$4(AsyncPromise.kt:96)
	at com.intellij.util.concurrency.ContextBiConsumer.accept(ContextBiConsumer.java:33)
	at org.jetbrains.concurrency.AsyncPromise$whenComplete$1.invoke(AsyncPromise.kt:114)
	at org.jetbrains.concurrency.AsyncPromise$whenComplete$1.invoke(AsyncPromise.kt:112)
	at org.jetbrains.concurrency.AsyncPromise.whenComplete$lambda$6(AsyncPromise.kt:112)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at org.jetbrains.concurrency.AsyncPromise.cancel(AsyncPromise.kt:70)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.cancel(NonBlockingReadActionImpl.java:325)
	at org.jetbrains.concurrency.AsyncPromise.cancel(AsyncPromise.kt:73)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.cancel(NonBlockingReadActionImpl.java:636)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.submitOrScheduleCoalesced(NonBlockingReadActionImpl.java:422)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.submit(NonBlockingReadActionImpl.java:236)
	at com.redhat.devtools.lsp4ij.internal.PromiseToCompletableFuture.nonBlockingReadActionPromise(PromiseToCompletableFuture.java:158)
	at com.redhat.devtools.lsp4ij.internal.PromiseToCompletableFuture.init(PromiseToCompletableFuture.java:81)
	at com.redhat.devtools.lsp4ij.AbstractDocumentMatcher$CompletableFutureWrapper.<init>(AbstractDocumentMatcher.java:34)
	at com.redhat.devtools.lsp4ij.AbstractDocumentMatcher.matchAsync(AbstractDocumentMatcher.java:40)
	at com.redhat.devtools.lsp4ij.server.definition.LanguageServerFileAssociation.matchAsync(LanguageServerFileAssociation.java:169)
	at com.redhat.devtools.lsp4ij.LanguageServiceAccessor.lambda$getMatchedLanguageServerDefinitions$8(LanguageServiceAccessor.java:362)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at com.redhat.devtools.lsp4ij.LanguageServiceAccessor.getMatchedLanguageServerDefinitions(LanguageServiceAccessor.java:371)
	at com.redhat.devtools.lsp4ij.LanguageServiceAccessor.getMatchedLanguageServersWrappers(LanguageServiceAccessor.java:198)
	at com.redhat.devtools.lsp4ij.LanguageServiceAccessor.getLanguageServers(LanguageServiceAccessor.java:100)
	at com.redhat.devtools.lsp4ij.features.codeLens.LSPCodeLensSupport.getCodeLenses(LSPCodeLensSupport.java:67)
	at com.redhat.devtools.lsp4ij.features.codeLens.LSPCodeLensSupport.doLoad(LSPCodeLensSupport.java:58)
	at com.redhat.devtools.lsp4ij.features.codeLens.LSPCodeLensSupport.doLoad(LSPCodeLensSupport.java:43)
	at com.redhat.devtools.lsp4ij.features.AbstractLSPFeatureSupport.load(AbstractLSPFeatureSupport.java:105)
	at com.redhat.devtools.lsp4ij.features.AbstractLSPFeatureSupport.getFeatureData(AbstractLSPFeatureSupport.java:73)
	at com.redhat.devtools.lsp4ij.features.codeLens.LSPCodeLensSupport.getCodeLenses(LSPCodeLensSupport.java:52)
	at com.redhat.devtools.lsp4ij.features.codeLens.LSPCodeLensProvider.getCodeLenses(LSPCodeLensProvider.java:226)
	at com.redhat.devtools.lsp4ij.features.codeLens.LSPCodeLensProvider.computeCodeVision(LSPCodeLensProvider.java:105)
	at com.redhat.devtools.lsp4ij.features.codeLens.LSPCodeLensProvider.computeCodeVision(LSPCodeLensProvider.java:54)
	at com.intellij.codeInsight.codeVision.CodeVisionHost$calculateFrontendLenses$2.invoke(CodeVisionHost.kt:453)
	at com.intellij.codeInsight.codeVision.CodeVisionHost$calculateFrontendLenses$2.invoke(CodeVisionHost.kt:423)
	at com.intellij.codeInsight.codeVision.CodeVisionHost.executeOnPooledThread$lambda$11$lambda$10(CodeVisionHost.kt:495)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:217)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.codeInsight.codeVision.CodeVisionHost.executeOnPooledThread$lambda$11(CodeVisionHost.kt:495)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2478)
	... 61 more

**Comment by fbricon** [comment]
@mfortunat we merged fixes that should hopefully fix the series of issues you've reported. Until 0.0.1-20240430-130816 or more recent is finally accessible on the Nightly channel (Jetbrains is a bit slow to approve today), you can [manually install a CI build](https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-the-ci-builds) and try it out. Please let us know if you find any more problems.

**Comment by mfortunat** [comment]
Hi @fbricon, After the latest fixes in 0.0.1-20240427-012620, I haven't had any other issues, so so far, so good.
Anyway, I will LYK of any additional problems.
Thanks.

**Comment by angelozerr** [comment]
Thanks so much @mfortunat to take time to report your issues!

Dont hesitate to create another if you find problems. 

We hope to release soon.

**Comment by fbricon** [comment]
@mfortunat can we close this one?

**Comment by mfortunat** [comment]
Hi @fbricon,

Yes, I think it can be closed.

**Comment by angelozerr** [comment]
Let's close and if you find again a cancel problem, please create a new issue. Thanks.
