### ISSUE TITLE
This is new and probably deserves some further investigation

### ISSUE THREAD

**Issue by mfortunat** [redhat-developer/lsp4ij#241]
Same configuration:
--- --- --- --- ---
Important point: the project I'm currently working on DOES NOT use OpenAPI in any way.
--- --- --- --- ---
Unhandled exception in [ComponentManager(ProjectImpl@671856067), CoroutineName(com.intellij.codeInsight.navigation.CtrlMouseHandler2), StandaloneCoroutine{Cancelling}@4ffc7517, Dispatchers.EDT]

java.lang.IndexOutOfBoundsException: Wrong offset: 20793. Should be in range: [0, 20685]
	at com.intellij.openapi.editor.impl.LineSet.findLineIndex(LineSet.java:164)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber(DocumentImpl.java:1005)
	at com.redhat.devtools.lsp4ij.LSPIJUtils.toPosition(LSPIJUtils.java:296)
	at com.redhat.devtools.lsp4ij.LSPIJUtils.toTextDocumentPositionParamsCommon(LSPIJUtils.java:136)
	at com.redhat.devtools.lsp4ij.LSPIJUtils.toHoverParams(LSPIJUtils.java:148)
	at com.redhat.devtools.lsp4ij.features.documentation.LSPHoverSupport.getHover(LSPHoverSupport.java:56)
	at com.redhat.devtools.lsp4ij.features.documentation.LSPDocumentationProvider.generateDoc(LSPDocumentationProvider.java:112)
	at com.redhat.devtools.lsp4ij.features.documentation.LSPDocumentationProvider.getQuickNavigateInfo(LSPDocumentationProvider.java:65)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.getQuickNavigateInfo(CompositeDocumentationProvider.java:111)
	at com.intellij.codeInsight.navigation.SingleTargetElementInfo.generateInfo(SingleTargetElementInfo.java:28)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.computeDocumentationHint(PsiElementDocumentationTarget.kt:74)
	at com.intellij.codeInsight.navigation.CtrlMouseDataKt.targetCtrlMouseData(CtrlMouseData.kt:101)
	at com.intellij.codeInsight.navigation.CtrlMouseDataKt.symbolCtrlMouseData(CtrlMouseData.kt:55)
	at com.intellij.codeInsight.navigation.impl.CtrlMouseKt.ctrlMouseData(ctrlMouse.kt:25)
	at com.intellij.codeInsight.navigation.impl.TargetGTDActionData.ctrlMouseData(gtd.kt:55)
	at com.intellij.codeInsight.navigation.impl.GtduKt$toGTDUActionData$1.ctrlMouseData(gtdu.kt:70)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOrUsageHandler2.getCtrlMouseData(GotoDeclarationOrUsageHandler2.kt:41)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.getCtrlMouseData(GotoDeclarationAction.java:84)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler2$computeInReadAction$1.invoke(CtrlMouseHandler.kt:235)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler2$computeInReadAction$1.invoke(CtrlMouseHandler.kt:234)
	at com.intellij.lang.documentation.ide.impl.DocumentationTargetHoverInfoKt.injectedThenHost(DocumentationTargetHoverInfo.kt:76)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler2.computeInReadAction(CtrlMouseHandler.kt:234)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler2.access$computeInReadAction(CtrlMouseHandler.kt:74)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler2$compute$2$1.invoke(CtrlMouseHandler.kt:220)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler2$compute$2$1.invoke(CtrlMouseHandler.kt:219)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:108)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:38)
	at com.intellij.openapi.application.impl.RwLockHolder.tryRunReadAction(RwLockHolder.kt:310)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:958)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:36)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:155)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:34)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:320)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:309)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:31)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:78)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:65)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:44)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:40)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:58)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler2$compute$2.invokeSuspend(CtrlMouseHandler.kt:219)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ProjectImpl@671856067), CoroutineName(com.intellij.codeInsight.navigation.CtrlMouseHandler2), StandaloneCoroutine{Cancelled}@4ffc7517, Dispatchers.EDT]

**Comment by mfortunat** [comment]
BTW, the debug/errors notifications have been disabled for LSP4IJ, but these errors come out regardless

**Comment by fbricon** [comment]
openapi is used within IJ itself

**Comment by mfortunat** [comment]
👍

**Comment by angelozerr** [comment]
> BTW, the debug/errors notifications have been disabled for LSP4IJ, but these errors come out regardless

It is normal the errors comes from LSPIJ himself and not from the manguage server. So it means that it is a bug from lsp4ij

You can disable only error coming from language servers.

**Comment by fbricon** [comment]
@mfortunat please try version 0.0.1-20240425-091012 (or more recent) on the nightly channel, it should fix this issue. If not, please reopen this ticket.

**Comment by mfortunat** [comment]
Sorry, I was traveling back home and missed that specific version.
My current installed version is 0.0.1-20240427-012620.

I will let you know of any issue
