### ISSUE TITLE
Find usages on a Java file can generate many IDE internal errors.

### ISSUE THREAD

**Issue by mrglavas** [redhat-developer/lsp4ij#273]
While working on an unrelated issue I tried to find all usages of a particular class `AnAction` in my project. IntelliJ returned the correct results in the IDE but I noticed 20 errors logged as IDE internal errors (a couple examples below). They all look similar, complaining about read access coming through a class in LSP4iJ called `LSPUsageSearcher`. I reproduced this with the latest MicroShed version which is based on a snapshot of this project (from April 1st) on IntelliJ IDEA 2024.1.

![image](https://github.com/redhat-developer/lsp4ij/assets/890521/f74ec2a9-6bea-4fe7-96ca-7c0888e79c43)

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[ApplicationImpl pooled thread 14,4,main] 622491191 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 190305548
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:180)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:131)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:908)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getStubTree(ClsFileImpl.java:471)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getStub(ClsFileImpl.java:451)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getClasses(ClsFileImpl.java:136)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:335)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getMirror(ClsElementImpl.java:132)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getTextRange(ClsElementImpl.java:139)
	at org.microshed.lsp4ij.usages.LSPUsageSearcher.getPosition(LSPUsageSearcher.java:90)
	at org.microshed.lsp4ij.usages.LSPUsageSearcher.processElementUsages(LSPUsageSearcher.java:66)
        ...
```

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[ApplicationImpl pooled thread 14,4,main] 622491191 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 190305548
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:180)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:131)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:908)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getStubTree(ClsFileImpl.java:471)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getStub(ClsFileImpl.java:451)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getClasses(ClsFileImpl.java:136)
	at com.intellij.psi.impl.compiled.ClsFileImpl.setFileMirror(ClsFileImpl.java:295)
	at com.intellij.psi.impl.compiled.ClsFileImpl.lambda$getMirror$1(ClsFileImpl.java:351)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:269)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:277)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:277)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:268)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:350)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getMirror(ClsElementImpl.java:132)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getTextRange(ClsElementImpl.java:139)
	at org.microshed.lsp4ij.usages.LSPUsageSearcher.getPosition(LSPUsageSearcher.java:90)
	at org.microshed.lsp4ij.usages.LSPUsageSearcher.processElementUsages(LSPUsageSearcher.java:66)
	at com.intellij.find.findUsages.FindUsagesManager.lambda$createUsageSearcher$10(FindUsagesManager.java:403)
	at com.intellij.usages.impl.SearchForUsagesRunnable.searchUsages(SearchForUsagesRunnable.java:369)
	at com.intellij.usages.impl.SearchForUsagesRunnable.run(SearchForUsagesRunnable.java:352)
	at com.intellij.usages.impl.UsageViewManagerImpl$2.run(UsageViewManagerImpl.java:165)
        ...
```

**Comment by mrglavas** [comment]
It's the same version we've been trying to stabilize on: https://github.com/MicroShed/lsp4ij/tree/q0401. It's a snapshot from April 1st. @turkeylurkey

**Comment by angelozerr** [comment]
@mrglavas I cannot reproduce the issue but by reading stack trace, it seems it is a problem with read action.

PLease try my PR https://github.com/redhat-developer/lsp4ij/pull/274 if it doesn't work, please reopen the issue.

**Comment by mrglavas** [comment]
@angelozerr Thanks. I can confirm that this resolves the issue. If this helps to build a test case, I was reproducing it consistently when running "Find Usages" on a class which has no source in my project. I noticed when I ran that to find usages of `com.intellij.openapi.actionSystem.AnAction` in my project, IntelliJ started decompling the code in the background so perhaps that's what triggers it.

**Comment by angelozerr** [comment]
Glad it fixes your issue and thanks for reporting the issue.

Next step is to fix completion with boostrap.properties I have a PR with tests which fix the issue.

I just need to clean my code and add comments since lsp completion support is very hard to support all language server.

I have tests with your bootstrap ls, typescript ls, clojure ls.

I plan to write tests for mp ls, qute ls, go ls, rust ls which provides another complex usecases.

If you want to add tests with your another ls like jakarta ls or liberty ls dont hesitate to create PR once I will merge my PR.
