### ISSUE TITLE
IncorrectOperationException: Must not change document outside command or undo-transparent action

### ISSUE THREAD

**Issue by harry-xm** [redhat-developer/lsp4ij#480]
Two IDE exceptions were thrown when I clicked "2 implementations" from this screenshot.

![Screenshot](https://github.com/user-attachments/assets/842d642c-3102-40b9-9daf-347a9d3f044c)

```
java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState.NON_MODAL
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:136)
	at com.intellij.openapi.editor.impl.DocumentImpl.assertWriteAccess(DocumentImpl.java:694)
	at com.intellij.openapi.editor.impl.DocumentImpl.deleteString(DocumentImpl.java:567)
	at com.redhat.devtools.lsp4ij.LSPIJUtils.applyEdit(LSPIJUtils.java:980)
	at com.redhat.devtools.lsp4ij.LSPIJUtils.doApplyEdits(LSPIJUtils.java:935)
	at com.redhat.devtools.lsp4ij.LSPIJUtils.lambda$applyEdits$9(LSPIJUtils.java:899)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:85)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction(AnyThreadWriteThreadingSupport.kt:328)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction(AnyThreadWriteThreadingSupport.kt:322)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:900)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:84)
	at com.redhat.devtools.lsp4ij.LSPIJUtils.applyEdits(LSPIJUtils.java:899)
	at com.redhat.devtools.lsp4ij.LSPIJUtils.applyWorkspaceEdit(LSPIJUtils.java:714)
	at com.redhat.devtools.lsp4ij.LSPIJUtils.applyWorkspaceEdit(LSPIJUtils.java:673)
	at com.redhat.devtools.lsp4ij.commands.CommandExecutor.executeCommand(CommandExecutor.java:101)
	at com.redhat.devtools.lsp4ij.features.codeLens.LSPCodeLensProvider.lambda$createCodeVisionEntry$1(LSPCodeLensProvider.java:248)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:696)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$16(IdeEventQueue.kt:590)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithoutImplicitRead(AnyThreadWriteThreadingSupport.kt:117)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:590)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:397)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

```
com.intellij.util.IncorrectOperationException: Must not change document outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor
	at com.intellij.openapi.editor.impl.DocumentImpl.assertInsideCommand(DocumentImpl.java:899)
	at com.intellij.openapi.editor.impl.DocumentImpl.beforeChangedUpdate(DocumentImpl.java:873)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:818)
	at com.intellij.openapi.editor.impl.DocumentImpl.deleteString(DocumentImpl.java:577)
	at com.redhat.devtools.lsp4ij.LSPIJUtils.applyEdit(LSPIJUtils.java:980)
	at com.redhat.devtools.lsp4ij.LSPIJUtils.doApplyEdits(LSPIJUtils.java:935)
	at com.redhat.devtools.lsp4ij.LSPIJUtils.lambda$applyEdits$9(LSPIJUtils.java:899)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:85)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction(AnyThreadWriteThreadingSupport.kt:328)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction(AnyThreadWriteThreadingSupport.kt:322)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:900)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:84)
	at com.redhat.devtools.lsp4ij.LSPIJUtils.applyEdits(LSPIJUtils.java:899)
	at com.redhat.devtools.lsp4ij.LSPIJUtils.applyWorkspaceEdit(LSPIJUtils.java:714)
	at com.redhat.devtools.lsp4ij.LSPIJUtils.applyWorkspaceEdit(LSPIJUtils.java:673)
	at com.redhat.devtools.lsp4ij.commands.CommandExecutor.executeCommand(CommandExecutor.java:101)
	at com.redhat.devtools.lsp4ij.features.codeLens.LSPCodeLensProvider.lambda$createCodeVisionEntry$1(LSPCodeLensProvider.java:248)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:696)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$16(IdeEventQueue.kt:590)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithoutImplicitRead(AnyThreadWriteThreadingSupport.kt:117)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:590)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:397)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by angelozerr** [comment]
@harry-xm could you share your file please?

**Comment by angelozerr** [comment]
I have tried it but I cannot see any codelens since rust-analyzer returns an empy CodeLens array, why?

In vscode, here the LSP response:

```
[Trace - 12:22:40 AM] Received response 'codeLens/resolve - (26)' in 10234ms.
Result: {
    "range": {
        "start": {
            "line": 25,
            "character": 11
        },
        "end": {
            "line": 25,
            "character": 20
        }
    },
    "command": {
        "title": "2 implementations",
        "command": "rust-analyzer.showReferences",
        "arguments": [
            "file:///c:/Users/azerr/git/pingora/pingora-limits/src/estimator.rs",
            {
                "line": 25,
                "character": 11
            },
            [
                {
                    "uri": "file:///c:/Users/azerr/git/pingora/pingora-limits/src/estimator.rs",
                    "range": {
                        "start": {
                            "line": 29,
                            "character": 0
                        },
                        "end": {
                            "line": 84,
                            "character": 1
                        }
                    }
                },
                {
                    "uri": "file:///c:/Users/azerr/git/pingora/pingora-limits/benches/benchmark.rs",
                    "range": {
                        "start": {
                            "line": 68,
                            "character": 0
                        },
                        "end": {
                            "line": 76,
                            "character": 1
                        }
                    }
                }
            ]
        ]
    }
}
```

The problem comes from https://github.com/redhat-developer/lsp4ij/blob/29fe5a3bf855755c3da396f35320c7a82fde4a11/src/main/java/com/redhat/devtools/lsp4ij/commands/CommandExecutor.java#L101 since you have not defined the `rust-analyzer.showReferences` and WorkspaceEdit is built  from the arguments (I wonder if we should remove this code @fbricon ?)

To fix your issue,you must define the `rust-analyzer.showReferences` action. This arguments of `rust-analyzer.showReferences` command seems follow the same structure than standard vscode `editor.action.showReferences` command.

As LSP4IJ implement this vscode command, I suggest that you definein your IJ plugin the acton:

```xml
<actions>
    <action id="rust-analyzer.showReferences"
            class="com.redhat.devtools.lsp4ij.commands.editor.ShowReferencesAction"/>
</actions>

```

and you should see https://github.com/redhat-developer/lsp4ij/blob/main/docs/DeveloperGuide.md#editoractionshowreferences

**Comment by angelozerr** [comment]
Thanks @harry-xm for your feedback. I merged the PR.

For codelens thats strange because in my case I have never seen the codelens.

Please create a new issue with your problem but my main problem is that I dont see implementation codelens even after rust ls have finished and even if I update editor content. My lsp console shows every time an empty codelens.
