### ISSUE TITLE
Error while consuming 'textDocument/inlayHint' with language server 'Qute support'

### ISSUE THREAD

**Issue by ksdev-pl** [redhat-developer/lsp4ij#499]
Hello.

While editing a qute template and writing `{#i` with the intention to write `{#include...` (exception was after `{#i`).

![image](https://github.com/user-attachments/assets/0eb47858-ac94-4664-9c30-59ad579012d6)

```
Error while consuming 'textDocument/inlayHint' with language server 'Qute support'

org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$1(LanguageServerWrapper.java:260)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

**Comment by angelozerr** [comment]
@ksdev-pl thanks for reporting this issue.

The problem comes from the Qute language server. I created the issue https://github.com/redhat-developer/quarkus-ls/issues/991
