### ISSUE TITLE
Plugin LSP4IJ (0.7.0): Error while starting language server 'qute' (pid=null)

### ISSUE THREAD

**Issue by mr-mos** [redhat-developer/lsp4ij#596]
Using the latest IntelliJ on latest Windows version, I'm getting the following error when starting the IDE:

```
Error while consuming LSP 'textDocument/inlayHint' request

java.util.concurrent.ExecutionException: com.redhat.devtools.lsp4ij.server.CannotStartServerException: Error while starting language server 'qute' (pid=null)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.redhat.devtools.lsp4ij.internal.CompletableFutures.waitUntilDone(CompletableFutures.java:119)
	at com.redhat.devtools.lsp4ij.features.inlayhint.LSPInlayHintsProvider.doCollect(LSPInlayHintsProvider.java:66)
	at com.redhat.devtools.lsp4ij.features.AbstractLSPInlayHintsProvider$1.collect(AbstractLSPInlayHintsProvider.java:86)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:97)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation$lambda$1(InlayHintsPass.kt:60)
	at com.intellij.concurrency.ApplierCompleter.processArrayItem(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.processArray(ApplierCompleter.java:196)
	at com.intellij.concurrency.ApplierCompleter.execAll(ApplierCompleter.java:166)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgressAsync$3(JobLauncherImpl.java:103)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:279)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$2(ApplierCompleter.java:148)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:159)
	at com.intellij.concurrency.ApplierCompleter.wrapAndRun(ApplierCompleter.java:143)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgressAsync$4(JobLauncherImpl.java:103)
	at com.intellij.concurrency.JobLauncherImpl.safeIterate(JobLauncherImpl.java:168)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgressAsync(JobLauncherImpl.java:100)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:48)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation(InlayHintsPass.kt:52)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:118)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:36)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:426)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:417)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
```

**Comment by angelozerr** [comment]
Have you this problem when IJ is scanning files or indexing something?

Is Qute support is available after this error?

**Comment by mr-mos** [comment]
>> Have you this problem when IJ is scanning files or indexing something?
Yes, I think it's during scanning. At least it's when the project is loaded in IntelliJ.

>>Is Qute support is available after this error?
Syntax Highlighting works partly.

**Comment by angelozerr** [comment]
> Yes, I think it's during scanning. At least it's when the project is loaded in IntelliJ.

Great! I'm working on this issue with https://github.com/redhat-developer/lsp4ij/pull/570 (not a trivial issue)

**Comment by angelozerr** [comment]
@mr-mos could you please install:

 * https://github.com/redhat-developer/intellij-quarkus?tab=readme-ov-file#testing-nightly-builds
 * https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-the-ci-builds

and tell me if it is working better. The main idea is to start language servers only when all indexing step is finished for all projects. In this case Qute, Quarkus language servers starts and visit Java classes which are ready to collect data. The IJ startup should be a lot improved.

Any feedback are welcome!
