### ISSUE TITLE
"CannotStartProcessException: Unable to start language server" while starting pyright language server

### ISSUE THREAD

**Issue by xCirno1** [redhat-developer/lsp4ij#614]
I'm using PyCharm 2024.1.4 and trying to start Pyright as the Python language server. However, I encounter the following error:
```
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: Unable to start language server: ProcessStreamConnectionProvider [commands=[C:\Users\xCirno\anaconda3\envs\numsy\Scripts\pyright-python-langserver.exe, --stdio], workingDir=C:\Users\xCirno\PycharmProjects\numsy]
	at com.redhat.devtools.lsp4ij.server.ProcessStreamConnectionProvider.ensureIsAlive(ProcessStreamConnectionProvider.java:88)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$1(LanguageServerWrapper.java:251)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
This occurs when PyCharm attempts to start the `pyright-python-langserver.exe` located in my Anaconda environment.

**Comment by angelozerr** [comment]
If you open a terminal and you execute your ls start command, is it working?

**Comment by xCirno1** [comment]
Okay, so apparently starting the ls through terminal doesn't work either. It turns out that Pyright was still using the old directory even after I have changed it to the new one through your LSP options. After reinstalling Pyright, everything is working fine now. Sorry for the trouble!
